

# -v "$HOME/.m2":/root/.m2 - prevents unnecessary downloading
# -mvn X -e >> debug  -ff > fail fast   -Dmaven.test.skip=true > not compile, not run tests

FROM maven:3.6.0-jdk-8-alpine
RUN apk add bash
COPY ./.  /app
WORKDIR /app
#VOLUME /test-results
#ENTRYPOINT ["/bin/bash",  "ls"]
#run a script: mvn clean test && docker cp unittests_cont:target/surefire-reports $HOME/test-results

ENTRYPOINT ["mvn",  "test"]
# "clean",
#CMD mvn clean test && tail -f /dev/null



#COPY wait-for-it.sh /usr/bin
#RUN chmod +x /usr/bin/wait-for-it.sh
#COPY pom.xml /tmp/
#COPY src /tmp/src/
#WORKDIR /tmp/cd ID

# CMD : execute container; can be overriden in docker run ..... bash (eg) ; last CMD overwrites previous, only ONE CMD is possible


# VOLUME creates a mount point with the specified point  -v ~/data:/opt/sth/var

# mvn clean package exec:java